import Head from 'next/head';
import BottomBar from '../components/BottomBar';
import JobsFeed from '../components/Feeds/JobsFeed';
import ProfileSummary from '../components/Feeds/ProfileSummary';
import SideLinks from '../components/Feeds/SideLinks';
import SuggestedConnections from '../components/Feeds/SuggestedConnections';
import Layer from '../components/Layer';
import Navbar from '../components/Navbar';
import Post from '../components/Post';
import ShareBox from '../components/ShareBox';

export default function Home() {
    return (
        <div>
            <Head>
                <title>LinkedIn2</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layer>
                <div className="container py-10">
                    <div className="sm:grid sm:grid-cols-4 md:flex lg:grid lg:grid-cols-12 gap-8 lg:gap-6 xl:gap-10">
                        <div className="relative col-span-4 md:col-span-3 lg:col-span-3">
                            <div className="sticky top-20 left-0">
                                <ProfileSummary />
                                <SideLinks />
                            </div>
                        </div>
                        <div className="col-span-4 md:col-span-9 lg:col-span-6">
                            <div>
                                <ShareBox />

                                {/* post here... */}
                                <Post />
                                <Post />
                            </div>
                        </div>
                        <div className="hidden lg:block relative col-span-3">
                            <div className="sticky top-20 left-0 space-y-5">
                                <JobsFeed />
                                <SuggestedConnections />
                            </div>
                        </div>
                    </div>
                </div>
            </Layer>
        </div>
    );
}
